from pwn import *
p = connect('localhost', 9999)
p.sendline('HELO')
print p.recvline()
p.sendline('MAIL FROM:<bill@localhost.com>')
print p.recvline()
p.sendline('RCPT TO:<alice@localhost.com>')
print p.recvline()
p.sendline('DATA')
print p.recvline()
print p.recvline()
print p.recvline()
p.sendline('QUIT')
print p.recvline()
p.close()
